### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by imlouelle** [webpwnized/mutillidae#38]
im getting this error when i exec mutillidae on lamp i use kali linux 

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /opt/lampp/htdocs/mutillidae/classes/EncodingHandler.php on line 8

**Comment by webpwnized** [comment]
What version of PHP are you using?

**Comment by imlouelle** [comment]
I'm using PHP 8.2.2 (cli) (built: Feb  7 2023 11:27:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.2, Copyright (c), by Zend Technologies

**Comment by webpwnized** [comment]
I have not been able to reproduce the issue; however, the issue can be
caused by using early versions of PHP 7. You might check if PHP 7 is also
installed on the system, and if Mutillidae may be using the older version.
The version of PHP Mutillidae is using should be shown in the page footer
at the bottom of most pages.
